# Generated by Django 3.2.22 on 2023-10-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quanity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='productinventory',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
